### ISSUE TITLE
re trojan

### ISSUE THREAD

**Issue by hfc187** [zone117x/cryptonote-easy-miner#7]
windows defender picked up a trojan attached to the miner zip

**Comment by mohammed-alsiddeeq** [comment]
Yes,same here.
Never going to use it.

**Comment by domacikolaci** [comment]
ESET hasn't flagged it, probs just a false positive cause its a "Bitcoin Miner" ?

**Comment by SplittyDev** [comment]
It's not a virus.. It's flagged as trojan or virus because often, malware developers include _hidden_ bitcoin miners in their viruses to make a profit by using other people's CPU or GPU power without them realizing it..

If you are actually downloading a miner in order to.. well.. mine coins, then you should just ignore the virus warning. There is nothing wrong with this software.

Statements like "Never going to use it" are stupid.. This program is literally open source, you can read the code and see that it's not a virus.. And if you're paranoid about the precompiled binaries you can compile it yourself.

So.. yeah. Not a virus. Ignore the AV.

**Comment by xdsswar** [comment]
Good reply for those guys who never know all miners softwares are flagged as viruses . Example of it is minergate  , and  it is not a open source software but  many people are using it
